### PR TITLE
pbTests: Fix Issue With Windows VPC Not Running Tests

### LINKED ISSUE #2772: VPC - Windows 2012 Failure When Running Playbook Tests
See: [https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1552/console](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1552/console)

The build element of the VPC job is running ok, however the testJDKWin.sh script fails as per below ( or the link above )

Updating files: 100% (1635/1635), done. **22:46:43** Invalid option: -t **22:46:47** C:/vagrant/pbTestScripts/testJDKWin.sh: line 24: cd: TKG: No such file or directory **22:46:47** make: \*\*\* No rule to make target '\_extended.system'.  Stop. **22:46:47** \<Objs Version="1.1.0.1" xmlns="[http://schemas.microsoft.com/powershell/2004/04](http://schemas.microsoft.com/powershell/2004/04)">\<Obj S="progress" RefId="0">\<TN RefId="0">\<T>System.Management.Automation.PSCustomObject\</T>\<T>System.Object\</T>\</TN>\<MS>\<I64 N="SourceId">1\</I64>\<PR N="Record">\<AV>Preparing modules for first use.\</AV>\<AI>0\</AI>\<Nil />\<PI>-1\</PI>\<PC>-1\</PC>\<T>Completed\</T>\<SR>-1\</SR>\<SD> \</SD>\</PR>\</MS>\</Obj>\</Objs>Running python script **22:46:47**  This is what is in the 'inputArgs' var:   **22:46:47**  This is what is in the 'ipAddress' var: 127.0.0.1:55985 **22:46:47** 2 **22:46:47** Running :      Start-Process powershell.exe -Verb runAs; cd C:/tmp; sh C:/vagrant/pbTestScripts/testJDKWin.sh **22:46:47** Creating testLocation directory **22:46:47** Git cloning openjdk-tests **22:46:47** This option was unrecognized. **22:46:47** Usage : get.sh -platform|-p x64\_linux | x64\_mac | s390x\_linux | ppc64le\_linux | aarch64\_linux | ppc64\_aix **22:46:47**                 \[--jdk\_version|-j \] : optional. JDK version

### PR DESCRIPTION
**Pull request by steelhead31**
Amend testJDKWin.sh for correct paths to build JDKs, and path definition issues.

Fixes #2772 

##### Checklist

- [X] commit message has one of the [standard prefixes]
- [X] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

Successful VPC Run Here : 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1570/

### CODE REVIEW

File: ansible/pbTestScripts/testJDKWin.sh [hunk 1]
```diff
@@ -1,12 +1,21 @@
...
 
-# Script to execute System tests on the previously built JDK.
+# Relocate Built JDKS
+mv /cygdrive/c/tmp/workspace/build/src/build/*/images/jdk* c:/tmp
 
-mv /cygdrive/c/tmp/workspace/build/src/build/*/images/jdk* $HOME
-# Ensures to set it to the JDK, not JRE or different images
-export TEST_JDK_HOME=C:/cygwin64$(find ~ -maxdepth 1 -type d -name "*jdk*"|grep -v ".*jre"| grep -v ".*-image")
+# Remove Redundant Images
+rm -rf /cygdrive/c/tmp/*-debug-image
```
Comment (zdtsw) [inline ansible/pbTestScripts/testJDKWin.sh:7]: i thought the file is called *debugimage* and *testimage* without "-"

Comment (steelhead31) [reply ansible/pbTestScripts/testJDKWin.sh:7]: It appears on windows this is definitely what the VPC build produces, only the actual JDK is needed, so I remove the redundant bits to save a bit of disk space, as these windows vagrant boxes are starting to get quite large.

**Review by zdtsw — APPROVED** [review]

**Review by sxa — APPROVED** [review]
Since this has run through VPC I'm ok with it and should merge as-is, although we should also create a follow-on issue to sync this up with the non-windows version as far as possible as they seem to have got somewhat out of sync in terms of exactly how they work e.g.

```
mkdir -p $HOME/testLocation
[ ! -d $HOME/testLocation/aqa-tests ] && git clone https://github.com/adoptium/aqa-tests.git $HOME/testLocation/aqa-tests
# cd to aqa-tests as required by https://github.com/adoptium/aqa-tests/issues/2691#issue-932959102
cd $HOME/testLocation/aqa-tests
$HOME/testLocation/aqa-tests/get.sh
cd $HOME/testLocation/aqa-tests/TKG || exit 1
```
vs
```
cd testLocation
if [ ! -d "openjdk-tests" ];
then
        echo "Git cloning openjdk-tests"
        git clone https://github.com/adoptopenjdk/openjdk-tests
fi
cd openjdk-tests

./get.sh -T $HOME/testLocation/openjdk-tests -p x64_windows
```
